[[development.loggers]]
type = "console"

[[development.loggers]]
type = "file"
filename = "sqs.log"

[[staging.loggers]]
type = "file"
filename = "/var/log/sqs.log"

[[production.loggers]]
type = "file"
filename = "/var/log/sqs.log"
