# ------------------------------
# development
# ------------------------------

[development.queue]
watchInterval = 5000

[[development.loggers]]
type = "console"

[[development.loggers]]
type = "file"
filename = "sqs.log"

# ------------------------------
# staging
# ------------------------------

[staging.queue]
watchInterval = 5000

[[staging.loggers]]
type = "file"
filename = "/var/log/sqs.log"

# ------------------------------
# production
# ------------------------------

[production.queue]
watchInterval = 5000

[[production.loggers]]
type = "file"
filename = "/var/log/sqs.log"
