[[development.loggers]]
type = "console"
category = "development"

[[staging.loggers]]
type = "file"
filename = "/var/log/sqs.log"
staging = "development"

[[production.loggers]]
type = "file"
filename = "/var/log/sqs.log"
production = "development"
